# Generated by Django 5.0.3 on 2024-03-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_currentjob_useraccount_currentlocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contacType',
            new_name='contactType',
        ),
    ]
