# Generated by Django 5.0.3 on 2024-03-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_contactype_contact_contacttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactOwner',
            new_name='UserAccount',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skillOwner',
            new_name='UserAccount',
        ),
    ]
