# Generated by Django 5.0.3 on 2024-03-13 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='contactContent',
        ),
        migrations.RemoveField(
            model_name='card',
            name='contactType',
        ),
        migrations.AddField(
            model_name='card',
            name='cardBalance',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=19),
        ),
        migrations.AddField(
            model_name='card',
            name='cardName',
            field=models.TextField(default='Some new card', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='cardNumber',
            field=models.TextField(default=4539595809648596, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 16', regex='^.{16}$')]),
        ),
    ]
