# Generated by Django 5.0.3 on 2024-03-13 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_card_creationdate_card_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 0, 27, 39, 657087)),
        ),
        migrations.AlterField(
            model_name='card',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 12, 0, 27, 39, 657087)),
        ),
    ]
