# Generated by Django 5.0.3 on 2024-03-13 17:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_card_creationdate_alter_card_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cardCVV',
            field=models.TextField(default='000', validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 16', regex='^.{3}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 0, 48, 56, 625664)),
        ),
        migrations.AlterField(
            model_name='card',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 12, 0, 48, 56, 625664)),
        ),
    ]
