# Generated by Django 5.0.3 on 2024-03-13 17:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_card_cardcvv_alter_card_creationdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cardBalance',
            new_name='bal',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardCVV',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='cardNumber',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expirationDate',
        ),
        migrations.AddField(
            model_name='card',
            name='creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 0, 58, 42, 534072)),
        ),
        migrations.AddField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 12, 0, 58, 42, 534072)),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Some new transaction', max_length=50)),
                ('creationDate', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 0, 58, 42, 535072))),
                ('Card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.card')),
                ('UserAccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
