# Generated by Django 5.0.3 on 2024-03-13 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_rename_cardbalance_card_bal_rename_cardcvv_card_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='creationDate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 1, 24, 20, 873734)),
        ),
        migrations.AlterField(
            model_name='card',
            name='creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 1, 24, 20, 873734)),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 12, 1, 24, 20, 873734)),
        ),
    ]
