# Generated by Django 5.0.3 on 2024-03-14 11:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_transaction_creationdate_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='UserAccount',
        ),
        migrations.AlterField(
            model_name='card',
            name='creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 18, 20, 35, 969958)),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.TextField(default='000', validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 13', regex='^.{3}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 12, 18, 20, 35, 969958)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 18, 20, 35, 969958)),
        ),
    ]
