# Generated by Django 5.0.3 on 2024-03-14 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_remove_transaction_useraccount_alter_card_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='cardName',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='transactionName',
        ),
        migrations.RemoveField(
            model_name='card',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='creation',
        ),
        migrations.AddField(
            model_name='card',
            name='Ccreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 22, 29, 50, 113322)),
        ),
        migrations.AddField(
            model_name='card',
            name='Cexpiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 12, 22, 29, 50, 113322)),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Tcreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 14, 22, 29, 50, 113322)),
        ),
    ]
