# Generated by Django 3.2.25 on 2024-05-07 12:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_rename_name_card_cardname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='grad1',
            field=models.TextField(default='#FFFFFF', validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 7', regex='^.{7}$')]),
        ),
        migrations.AddField(
            model_name='card',
            name='grad2',
            field=models.TextField(default='#FFFFFF', validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 7', regex='^.{7}$')]),
        ),
        migrations.AddField(
            model_name='card',
            name='gradDeg',
            field=models.IntegerField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='Ccreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 7, 19, 24, 13, 239967)),
        ),
        migrations.AlterField(
            model_name='card',
            name='Cexpiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 5, 19, 24, 13, 239967)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Tcreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 7, 19, 24, 13, 239967)),
        ),
    ]
