# Generated by Django 3.2.25 on 2024-05-07 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20240507_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Ccreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 7, 20, 43, 59, 698549)),
        ),
        migrations.AlterField(
            model_name='card',
            name='Cexpiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 5, 20, 43, 59, 698549)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Tcreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 7, 20, 43, 59, 698549)),
        ),
    ]
